version: 1
# https://www.reddit.com/r/FastAPI/comments/v969fr/logging_not_working_in_routes/
disable_existing_loggers: false

formatters:
  standard:
      format: "%(asctime)s - %(name)s.%(funcName)s - %(levelname)s - %(message)s"
  error:
      format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: standard
    filename: logs/warn+.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
#  strike:
#  main:
#    level: DEBUG
#    handlers: [console, file_handler]
#    propagate: no

  root:
    level: NOTSET
    handlers: [console, file_handler]
    propogate: yes