[tool.poetry]
name = "strike"
version = "0.1.0"
description = ""
authors = ["Aleksei Khatkevich <qwerty12345@disroot.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.95"
uvicorn = "0.22.*"
uvloop = "0.17.*"
httptools = "0.5.*"
sqlalchemy = "2.0.*"
orjson = "3.8.*"
asyncpg = "0.27.*"
pytest = "7.*"
alembic = "^1.11"
python-dotenv = "^1.0.0"
email-validator = "^2.0.0"
bcrypt = "4.*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
