"""RM FK from Place

Revision ID: 036a68f0e863
Revises: 5142100d5388
Create Date: 2023-06-29 15:31:07.428052

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '036a68f0e863'
down_revision = '5142100d5388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_places_name', 'places', type_='unique')
    op.create_unique_constraint(op.f('uq_places_name'), 'places', ['name'])
    op.drop_constraint('fk_places_region_name_regions', 'places', type_='foreignkey')
    op.drop_column('places', 'region_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('region_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_places_region_name_regions', 'places', 'regions', ['region_name'], ['name'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(op.f('uq_places_name'), 'places', type_='unique')
    op.create_unique_constraint('uq_places_name', 'places', ['name', 'region_name'])
    # ### end Alembic commands ###
