"""Create KafKaRoutes

Revision ID: 20558ef6f454
Revises: 2b9e48c5c5f7
Create Date: 2023-08-28 10:33:10.369624

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20558ef6f454'
down_revision = '2b9e48c5c5f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('kafka_routes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('duration', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('linestring', Geography(geometry_type='LINESTRING', spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('duration'), '&&'), (sa.column('user_id'), '='), using='gist', name='duration_user_id_exc_c'),
    sa.CheckConstraint('user_id >= 1', name=op.f('ck_kafka_routes_user_id_gte_1')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kafka_routes'))
    )
    op.create_geospatial_index('idx_kafka_routes_linestring', 'kafka_routes', ['linestring'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_kafka_routes_duration'), 'kafka_routes', ['duration'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_kafka_routes_duration'), table_name='kafka_routes')
    op.drop_geospatial_index('idx_kafka_routes_linestring', table_name='kafka_routes', postgresql_using='gist', column_name='linestring')
    op.drop_geospatial_table('kafka_routes')
    # ### end Alembic commands ###
