"""common passwords table

Revision ID: 264769e69860
Revises: 4b64005f3917
Create Date: 2023-06-02 12:28:43.097513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264769e69860'
down_revision = '4b64005f3917'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_passwords',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('password', sa.Text(collation='english_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_common_passwords'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('common_passwords')
    # ### end Alembic commands ###
