"""Create Conflict  model

Revision ID: 2b9e48c5c5f7
Revises: a8ae6eb46ce1
Create Date: 2023-08-11 12:19:36.062431

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b9e48c5c5f7'
down_revision = 'a8ae6eb46ce1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('type', postgresql.ENUM('PAYMENT', 'LAYOFF', 'LIQUIDATION', 'OTHER', 'DISMISSAL', 'MANAGEMENT_POLITICS', 'WORK_CONDITIONS', 'LABOR_HOURS', 'COLLECTIVE_AGREEMENT', 'PAYMENT_DELAY', 'LABOUR_RIGHTS', name='conflicttypes'), nullable=False),
    sa.Column('duration', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('enterprise_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('results', sa.String(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('success_rate >= 0 AND success_rate <= 1', name=op.f('ck_conflicts_success_rate_between_0_1')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_conflicts_enterprise_id_enterprises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflicts'))
    )
    op.create_index(op.f('ix_conflicts_duration'), 'conflicts', ['duration'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_conflicts_duration'), table_name='conflicts')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
