"""Create Place model

Revision ID: 2cb35c564c53
Revises: e77843cce691
Create Date: 2023-06-18 13:14:42.249135

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '2cb35c564c53'
down_revision = 'e77843cce691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('places',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=128, collation='russian_ci'), nullable=False),
    sa.Column('address', sa.String(length=256, collation='russian_ci'), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('coordinates', Geography(geometry_type='POINT', spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.ForeignKeyConstraint(['region_name'], ['regions.name'], name=op.f('fk_places_region_name_regions'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places')),
    sa.UniqueConstraint('name', 'region_name', name=op.f('uq_places_name'))
    )
    op.create_geospatial_index('idx_places_coordinates', 'places', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_places_coordinates', table_name='places', postgresql_using='gist', column_name='coordinates')
    op.drop_geospatial_table('places')
    # ### end Alembic commands ###
