"""Add counter into Region

Revision ID: 3b2701c77fc4
Revises: ce6ba374829a
Create Date: 2023-06-23 15:20:17.673423

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '3b2701c77fc4'
down_revision = 'ce6ba374829a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_geospatial_column('regions', sa.Column('contour', Geography(geometry_type='MULTIPOLYGON', spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=False))
    op.create_geospatial_index('idx_regions_contour', 'regions', ['contour'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_regions_contour', table_name='regions', postgresql_using='gist', column_name='contour')
    op.drop_geospatial_column('regions', 'contour')
    # ### end Alembic commands ###
