"""Create strike to place m2m table

Revision ID: 3d4b0d162e48
Revises: 2cb35c564c53
Create Date: 2023-06-18 14:27:57.910325

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '3d4b0d162e48'
down_revision = '2cb35c564c53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strike_to_place_associations',
    sa.Column('strike_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_strike_to_place_associations_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strike_id'], ['strikes.id'], name=op.f('fk_strike_to_place_associations_strike_id_strikes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('strike_id', 'place_id', name=op.f('pk_strike_to_place_associations'))
    )
    op.alter_column('places', 'coordinates',
               existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'coordinates',
               existing_type=Geography(geometry_type='POINT', from_text='ST_GeogFromText', name='geography'),
               type_=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_table('strike_to_place_associations')
    # ### end Alembic commands ###
