"""Modify Enterprise

Revision ID: 3f2bf264a901
Revises: 036a68f0e863
Create Date: 2023-07-04 10:50:28.278574

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '3f2bf264a901'
down_revision = '036a68f0e863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprises', 'created_at')
    # ### end Alembic commands ###
