"""Add idx into Crudlog

Revision ID: 40ef7efda126
Revises: ba74b61c3f5d
Create Date: 2023-07-19 14:19:45.400705

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '40ef7efda126'
down_revision = 'ba74b61c3f5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('operation_ts_brin_idx', 'crud_logs', ['operation_ts'], unique=False, postgresql_using='brin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('operation_ts_brin_idx', table_name='crud_logs', postgresql_using='brin')
    # ### end Alembic commands ###
