"""Create excl. constr. on close points

Revision ID: 44042a93ecfc
Revises: 3d4b0d162e48
Create Date: 2023-06-19 10:28:15.205877

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from geoalchemy2.functions import ST_Buffer
# revision identifiers, used by Alembic.
revision = '44042a93ecfc'
down_revision = '3d4b0d162e48'
branch_labels = None
depends_on = None

constraint_name = 'close_points_exc_constraint'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
    f"""
    ALTER TABLE places ADD constraint {constraint_name} EXCLUDE USING gist (
   (st_buffer(coordinates, 100, 'quad_segs=1')) WITH &&
);
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name, 'places')
    # ### end Alembic commands ###
