"""Add strike  table

Revision ID: 476dbaa0c8c3
Revises: b12fa9819624
Create Date: 2023-06-15 15:44:46.659706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476dbaa0c8c3'
down_revision = 'b12fa9819624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strikes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('planned_on_date', sa.Date(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('overall_num_of_employees_involved', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('num_nonnulls("started_at", "finished_at", "planned_on_date") >= 1', name=op.f('ck_strikes_one_of_dates_is_not_null')),
    sa.CheckConstraint('finished_at > started_at', name=op.f('ck_strikes_finished_gt_started')),
    sa.CheckConstraint('overall_num_of_employees_involved >= 1', name=op.f('ck_strikes_overall_num_of_employees_involved_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strikes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strikes')
    # ### end Alembic commands ###
