"""Create PostGis extension

Revision ID: 58a12b808941
Revises: 64244710c802
Create Date: 2023-06-18 12:26:32.386932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '58a12b808941'
down_revision = '64244710c802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("CREATE EXTENSION IF NOT EXISTS postgis;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("DROP EXTENSION IF EXISTS postgis;"))
    # ### end Alembic commands ###
