"""Add user_id  into Crudlog

Revision ID: 677bd6fa315f
Revises: 40ef7efda126
Create Date: 2023-07-19 14:57:39.471698

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '677bd6fa315f'
down_revision = '40ef7efda126'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crud_logs', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_crud_logs_user_id_users'), 'crud_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(op.f('fk_crud_logs_user_id_users'), 'crud_logs', type_='foreignkey')
    op.drop_column('crud_logs', 'user_id')
    # ### end Alembic commands ###
