"""rm spatial index

Revision ID: 7e1063c4455e
Revises: 7d1ab8a4b9b0
Create Date: 2023-06-19 12:26:27.307380

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = '7e1063c4455e'
down_revision = '7d1ab8a4b9b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'coordinates',
               existing_type=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               type_=Geography(geometry_type='POINT', spatial_index=False, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    op.drop_geospatial_index('idx_places_coordinates', table_name='places', column_name='coordinates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_index('idx_places_coordinates', 'places', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.alter_column('places', 'coordinates',
               existing_type=Geography(geometry_type='POINT', spatial_index=False, from_text='ST_GeogFromText', name='geography'),
               type_=Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'),
               existing_nullable=True)
    # ### end Alembic commands ###
