"""Add region table

Revision ID: 97952446d9ed
Revises: 46bb8ffd1179
Create Date: 2023-06-16 15:58:53.111316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97952446d9ed'
down_revision = '46bb8ffd1179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_regions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions')
    # ### end Alembic commands ###
