"""Add Enterprise model

Revision ID: b46e2c5ec72b
Revises: 97952446d9ed
Create Date: 2023-06-16 17:45:29.467883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46e2c5ec72b'
down_revision = '97952446d9ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('place', sa.Text(collation='russian_ci'), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('field_of_activity', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_name'], ['regions.name'], name=op.f('fk_enterprises_region_name_regions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enterprises')),
    sa.UniqueConstraint('name', 'region_name', 'place', name=op.f('uq_enterprises_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enterprises')
    # ### end Alembic commands ###
