"""create CRUDTypes model

Revision ID: ba74b61c3f5d
Revises: 051ee12789b9
Create Date: 2023-07-19 14:11:19.286610

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba74b61c3f5d'
down_revision = '051ee12789b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crud_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('object_type', sa.String(length=255), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('action', postgresql.ENUM('create', 'update', 'delete', 'add', 'remove', name='crudtypes'), nullable=False),
    sa.Column('operation_ts', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crud_logs'))
    )
    op.create_index('type_object_id_idx', 'crud_logs', ['object_type', 'object_id'], unique=False, postgresql_include=['action'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('type_object_id_idx', table_name='crud_logs', postgresql_include=['action'])
    op.drop_table('crud_logs')
    # ### end Alembic commands ###
