"""hash common passwords

Revision ID: c5f8082036b7
Revises: 264769e69860
Create Date: 2023-06-02 12:39:45.095479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f8082036b7'
down_revision = '264769e69860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password_hash_idx', 'common_passwords', ['password'], unique=False, postgresql_using='hash', postgresql_with={'fillfactor': 100})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password_hash_idx', table_name='common_passwords', postgresql_using='hash', postgresql_with={'fillfactor': 100})
    # ### end Alembic commands ###
