"""Add unique idx into Strike

Revision ID: ce6ba374829a
Revises: b01ba6d159de
Create Date: 2023-06-19 17:03:17.177910

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision = 'ce6ba374829a'
down_revision = 'b01ba6d159de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(op.f('uq_strikes_planned_on_date'), 'strikes', ['planned_on_date', 'enterprise_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_strikes_planned_on_date'), 'strikes', type_='unique')

    # ### end Alembic commands ###
