"""Create Place model

Revision ID: e77843cce691
Revises: 58a12b808941
Create Date: 2023-06-18 12:43:13.127217

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e77843cce691'
down_revision = '58a12b808941'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=128, collation='russian_ci'), nullable=False),
    sa.Column('address', sa.String(length=256, collation='russian_ci'), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['region_name'], ['regions.name'], name=op.f('fk_places_region_name_regions'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places')),
    sa.UniqueConstraint('name', 'region_name', name=op.f('uq_places_name'))
    )
    # op.create_index('idx_places_coordinates_new', 'places', ['coordinates'], unique=False, postgresql_using='gist')
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index('idx_places_coordinates', table_name='places', postgresql_using='gist')
    op.drop_table('places')
    # ### end Alembic commands ###
