"""Add user role into int. table

Revision ID: ea4877645996
Revises: fc3dbf4ac3b3
Create Date: 2023-06-16 12:34:55.088632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ea4877645996'
down_revision = 'fc3dbf4ac3b3'
branch_labels = None
depends_on = None


enum_members = ('employee', 'union_member', 'observer', 'guest', 'spy', 'volunteer', 'coordinator')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = postgresql.ENUM(*enum_members, name='userrole')
    userrole.create(op.get_bind())

    op.add_column('strike_to_user_associations', sa.Column('role', sa.Enum(*enum_members, name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strike_to_user_associations', 'role')
    userrole = postgresql.ENUM(*enum_members, name='userrole')
    userrole.drop(op.get_bind())
    # ### end Alembic commands ###
