"""adjust constr. to a duration

Revision ID: fc3dbf4ac3b3
Revises: f88b5faf6996
Create Date: 2023-06-16 10:37:43.304762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3dbf4ac3b3'
down_revision = 'f88b5faf6996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'one_of_dates_is_not_null',
        'strikes',
        r'num_nonnulls("duration", "planned_on_date") >= 1',
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('one_of_dates_is_not_null', 'strikes')
    # ### end Alembic commands ###
